### ISSUE TITLE
Depth Does Not Increase With Section Nesting

### ISSUE THREAD

**Issue by HughxDev** [hoyois/html5outliner#1]
When I try to get the depth of heading elements, they always return a value of 1, as opposed to their section depth (body > article > h1 should be depth 2), regardless of where they are located in the document.

**Comment by hoyois** [comment]
It's been some time since I thought about this, but I'm pretty sure I'm following the algorithm strictly. The definition of depth seemed pretty unintuitive to me as well when I first parsed it. It's a measure of how deeply the heading is within its closest sectioning element parent. So if all sections are explicit, then all headings will have depth 1.

depth = <i>the number of sections that are ancestors of s in the outline that s finds itself in when the outlines are created</i> + 1, where s is the section associated to the heading.

In a situation like body > section > h1 h2 h1, the outline the headings find themselves in is the outline of the enclosing section element (the "current outlinee"), which looks like

section1
— section1.1
section2

so depth of each h1 is 0+1, and depth of the h2 is 1+1. Would you still interpret the definition differently?

**Comment by HughxDev** [comment]
I don’t know; the definition is very confusing. I would _think_ that depth would correspond to the level of nesting… is there a way to determine that at all?

**Comment by hoyois** [comment]
You should [submit a bug report](http://www.whatwg.org/specs/web-apps/current-work/multipage/sections.html#outline-depth) and ask them to clarify the definition. I did that last year for the algorithm itself and they modified it as a result (it used to have 8 points, and two of them were vacuous).

**Comment by hoyois** [comment]
Anyway I'm closing this for the time being. Please reopen it if you get more info.

**Comment by hoyois** [comment]
By the way, an argument in favor this weird definition is that the more obvious notion of depth is so easily computed by other means (just look at the tree of sections!) that it would be redundant to add a property for it.

**Comment by HughxDev** [comment]
What I am trying to do is add specific attributes (with jQuery) to headings depending on where they appear in the outline tree, without reimplementing the algorithm myself. If it’s easy to do, would you mind giving me an example?

**Comment by hoyois** [comment]
How about this:

var section = heading.associatedSection;
var depth = 0;
while(section = section.parentSection) ++depth;

**Comment by HughxDev** [comment]
That works, thanks! Maybe it is redundant in HTML; I may still raise the issue, but either way you should consider adding that as a property in your code, perhaps as "nesting" or "level" or similar, in case others are similarly confused.

**Comment by HughxDev** [comment]
Just posted to the WHATWG about this and was informed that the more intuitive interpretation is in fact correct; the spec is referring to the number of ancestor sections within the entire document outline, not just the current outlinee.

**Comment by hoyois** [comment]
I'll change it then, thanks!

**Comment by hoyois** [comment]
Done. I simply made the depth property into a getter that does exactly what I posted before.
